# This is a basic workflow to help you get started with Actions

name: Upayments

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
            version: 12
      - name: npm install
  
        run: npm install #will run npm install command
      - name: build react app
        run:  CI=false npm run build # CI=false to ignore warnings         
      - name: install surge
        run: npm install -g surge
      - name: deploy react app on surge
        run: surge ./build https://upayments.surge.sh/ --token ${{secrets.surge_token}}
